In [1]:
import numpy as np
a = np.array([1,2,3])
print("A:\n%s"%a)
print("type:%s"%type(a))
print("shape:%s"%a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)
b = np.array([[1,2,3],[4,5,6]])
print("\nshape of b:", b.shape)
print(b[0,0], b[0,1], b[1,0])
a = np.zeros((2,2))
print("\nAll zeros matrix:\n%s"%a)
b = np.ones((1,2))
print("\nAll one matrix:\n%s"%b)
d = np.eye(2)
print("\nIdentity matrix:\n%s"%d)
e = np.random.random((2,2))
print("\nRandom matrix:\n%s"%e)
print("\nVectorized sum example\n")
x = np.array([[1,2],[3,4]])
print("x:\n%s"%x)
print("sum:%s"%np.sum(x))
print("sum axis=0:%s"%np.sum(x,axis=0))
print("sum axis=1:%s"%np.sum(x,axis=1))
a = np.array([2,2,1])
b = np.array([1,2,2])
dp = np.dot(a,b)
print("Dot product:%s\n"%dp)
op = np.outer(a,b)
print("Outer product:%s\n"%op)
ep = np.multiply(a,b)
print("Element wise product:%s\n"%ep)
import numpy as np
x = np.array([[1,2],[3,4]])
print("Original x:\n%s"%x)
print("Transpose of x:\n%s"%x.T)
from numpy import array
from scipy.linalg import svd
A = array([[1,2],[3,4],[5,6]])
print("A:\n%s"%A)
U, s, VT = svd(A)
print("\nU:\n%s"%U)
print("\nS:\n%s"%s)
print("\nVT:\n%s"%VT)

      
      
      

A:
[1 2 3]
type:<class 'numpy.ndarray'>
shape:3
1 2 3
[5 2 3]

shape of b: (2, 3)
1 2 4

All zeros matrix:
[[0. 0.]
 [0. 0.]]

All one matrix:
[[1. 1.]]

Identity matrix:
[[1. 0.]
 [0. 1.]]

Random matrix:
[[0.27649653 0.78255546]
 [0.22296479 0.10358173]]

Vectorized sum example

x:
[[1 2]
 [3 4]]
sum:10
sum axis=0:[4 6]
sum axis=1:[3 7]
Dot product:8

Outer product:[[2 4 4]
 [2 4 4]
 [1 2 2]]

Element wise product:[2 4 2]

Original x:
[[1 2]
 [3 4]]
Transpose of x:
[[1 3]
 [2 4]]
A:
[[1 2]
 [3 4]
 [5 6]]

U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

S:
[9.52551809 0.51430058]

VT:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [2]:
import pandas as pd

# Corrected Data Dictionary for customers1.csv
data_dict1 = {
    'customer ID': [1,2,3,4,5,6,7,8,9,10],
    'Gender': ['male','female','female','male','male','female','female','male','male','female'],
    'Age': [20,21,19,18,25,26,32,41,20,19],
    'Annual Income(k$)': [10,20,30,10,25,60,70,15,21,27],
    'Spending Score': [30,50,58,84,90,65,32,46,12,56]
}

data1 = pd.DataFrame(data_dict1)
data1.to_csv("customers1.csv", index=False)
print("Data1:\n", data1)

# Corrected Data Dictionary for customers2.csv
data_dict2 = {
    'customer ID': [11,12,13,14,15,16,17,18,19,20],
    'Gender': ['male','female','male','male','male','female','male','female','female','male'],
    'Age': [23,33,41,18,25,26,32,41,20,19],
    'Annual Income(k$)': [10,20,30,10,25,60,70,15,21,27],
    'Spending Score': [38,54,48,99,94,66,44,51,12,56]
}

data2 = pd.DataFrame(data_dict2)
data2.to_csv("customers2.csv", index=False)
print("Data2:\n", data2)

# Read CSVs and concatenate
df1 = pd.read_csv("customers1.csv")
df2 = pd.read_csv("customers2.csv")

df = pd.concat([df1, df2], ignore_index=True)
print("\nConcatenated Data:\n", df)


Data1:
    customer ID  Gender  Age  Annual Income(k$)  Spending Score
0            1    male   20                 10              30
1            2  female   21                 20              50
2            3  female   19                 30              58
3            4    male   18                 10              84
4            5    male   25                 25              90
5            6  female   26                 60              65
6            7  female   32                 70              32
7            8    male   41                 15              46
8            9    male   20                 21              12
9           10  female   19                 27              56
Data2:
    customer ID  Gender  Age  Annual Income(k$)  Spending Score
0           11    male   23                 10              38
1           12  female   33                 20              54
2           13    male   41                 30              48
3           14    male   18            